# mods.toml - Mod configuration file for FML mod loader

modLoader="javafml" # Type of mod loader
loaderVersion="${loader_version_range}" # FML version range
license="${mod_license}" # Mod license
issueTrackerURL="https://euphoriapatches.com/discord" # Optional issue tracker URL

[[mods]]
modId="${mod_id}" # Mod ID
version="${mod_version}" # Mod version
displayName="${mod_name}" # Mod name
displayURL="https://euphoriapatches.com" # Optional mod homepage
logoFile="logo.png" # Optional logo file
authors="${mod_authors}" # Optional authors
displayTest="IGNORE_ALL_VERSION" # Controls server connection screen behavior
description='''${mod_description}''' # Mod description

[[mixins]]
config="${mod_id}.mixins.json" # Mixin config file

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
